### ISSUE TITLE
Implementation to your Project in my app

### ISSUE THREAD

**Issue by gazy98** [signalwareltd/rtl_tcp_andro-#25]
Hallo i would like to implement your project into my app so you dont need to install one extra application. What are the stepps to do that? 

thank you for your help!

**Comment by martinmarinov** [comment]
Please note that this app is licensed under GPL so only apps that are open source under GPL can bundle and distribute these libraries.

That being said there is no easy solution on how to do this so you will have to fork the driver.

You can see how the UI part of the app talks to the underlying hardware so you can possibly replicate that in your own app.

The challenge will also be to get the native libraries to compile since with the version of gradle your app is using. The issue is thay at the moment the driver is using a legacy unsupported version of gradle.
